import type { NextPage } from 'next'
import Head from 'next/head'
import {Button} from "@mui/material";
import useHomeStyles from "../styles/home.styles";

const Home: NextPage = () => {

    const classes = useHomeStyles()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.root}>
        <Button>Hello World</Button>
      </main>
    </div>
  )
}

export default Home
